---
title: "RMW"
author: "Yutaka Kuroki"
date: "2017年12月18日"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# はじめに
RMWの作成

```{r setup}
library(xts)
library(tidyverse)
library(lubridate)
source("E:/Git/Bloomberg/function/BB.merge.R")
tmp <- BB.merge("E:/Git/Bloomberg/data/ROE.csv")
```

```{r assets}
d.tmp <- read.csv("E:/Git/Bloomberg/data/assets.csv")
rownames(d.tmp) <- d.tmp[,1]
d <- data.frame(date = as.Date(rownames(d.tmp)[-1]),
                apply(d.tmp[,-1] %>% na.omit(), 2, function(x){diff(log(x))}))
```


```{r ROE}
ROE <- tmp %>% 
  do.call("rbind",.) %>% 
  as.data.frame() %>% 
  .[1:653,] %>%  # 最近のやつはまだ会計出てないの多いしね。
  na.locf()
ROE.diff <- apply(ROE, 2,function(x) diff(log(x))) 
ROE.diff[ROE.diff == 0] <- NA
ROE.diff <- na.locf(ROE.diff)
ROE.diff[is.na(ROE.diff) == TRUE] <- 0
ROE.diff <- rownames_to_column(as.data.frame(ROE.diff), var="date")
ROE.rate <- ROE.diff %>% 
  mutate(year = year(date),
         month = month(date)) %>% 
  group_by(year,month) %>% 
  summarise_all(funs(mean(.,na.rm = TRUE))) %>% 
  select(-date) %>% 
  gather(key,value,-year,-month) %>% 
  ungroup() %>% 
  group_by(year,month) %>% 
  arrange(year,month,value) %>% 
  mutate(rank = min_rank(desc(value))) %>% 
  ungroup()
```


```{r name}
robust_name <- ROE.rate %>% 
  filter(rank > max(rank)*2/3) %>% 
  select(year, month, key) %>% 
  group_by(year, month) %>% 
  nest() %>% 
  mutate(name = map(data,~unlist(.x))) %>% 
  select(-data)

weak_name <- ROE.rate %>% 
  filter(rank < max(rank)*1/3) %>% 
  select(year, month, key) %>% 
  group_by(year, month) %>% 
  nest() %>% 
  mutate(name = map(data,~unlist(.x))) %>% 
  select(-data)
```

```{r return}
robust <- d %>% 
  mutate(year = year(date),
         month = month(date)) %>% 
  group_by(year,month) %>% 
  nest() %>% 
  inner_join(robust_name, by=c("year","month")) %>% 
  mutate(port = map2(data,name,
                     ~select(.x, one_of(.y)))) %>% 
  mutate(return = map2(port,data,
                       ~data.frame(date=.y$date, robust=apply(.x, 1, mean)))) %>% 
  select(return) %>% 
  unnest()

weak <- d %>% 
  mutate(year = year(date),
         month = month(date)) %>% 
  group_by(year,month) %>% 
  nest() %>% 
  inner_join(weak_name, by=c("year","month")) %>% 
  mutate(port = map2(data,name,
                     ~select(.x, one_of(.y)))) %>% 
  mutate(return = map2(port,data,
                       ~data.frame(date=.y$date, weak=apply(.x, 1, mean)))) %>% 
  select(return) %>% 
  unnest()

RMW <- robust %>% 
  inner_join(weak, by="date") %>% 
  mutate(return = robust - weak) %>% 
  select(-robust, -weak, RMW = return)
```

