---
title: "CMA"
author: "Yutaka Kuroki"
date: "2017年12月18日"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# はじめに
MOMの作成

```{r setup}
library(xts)
library(tidyverse)
library(lubridate)
source("E:/Git/Bloomberg/function/BB.merge.R")
tmp <- BB.merge("E:/Git/Bloomberg/data/AG.csv")
```

```{r assets}
d.tmp <- read.csv("E:/Git/Bloomberg/data/assets.csv")
rownames(d.tmp) <- d.tmp[,1]
d <- data.frame(date = as.Date(rownames(d.tmp)[-1]),
                apply(d.tmp[,-1] %>% na.omit(), 2, function(x){diff(log(x))}))
```

```{r}
AG <- do.call("rbind",tmp) %>% 
  as.data.frame() %>% 
  apply(2, function(x) diff(log(x))) %>% 
  as.data.frame() %>% 
  rownames_to_column("date") 

AG[AG==0] <- NA
AG <- na.locf(AG)  
AG[is.na(AG)==TRUE] <- 0
ag <- AG %>% 
  mutate(year = year(date),
         month = month(date)) %>% 
  group_by(year, month) %>% 
  select(-date) %>% 
  mutate_all(funs(as.numeric(.)))%>% 
  nest() %>% 
  ungroup() %>% 
  filter(year > 2014) %>% 
  mutate(data = map(data, 
                    ~ data.frame(AG = apply(.x,2,function(x) mean(x, na.rm=TRUE))) %>% 
                      rownames_to_column("key")))
ag <- ag %>% 
  mutate(data = map(data, ~.x %>% mutate(rank = min_rank(desc(AG))))) %>% 
  unnest() 

high <- ag %>% 
  group_by(year, month) %>% 
  filter(rank < n()*1/3) %>% 
  nest() %>% 
  mutate(high = map(data, ~.x %>% select(key) %>% unlist())) %>% 
  select(-data)

low <- ag %>% 
  group_by(year, month) %>% 
  filter(rank > n()*2/3) %>% 
  nest() %>% 
  mutate(low = map(data, ~.x %>% select(key) %>% unlist())) %>%  
  select(-data)
```

```{r}
CMA <- d %>% 
  as_tibble() %>% 
  mutate(year = year(date),
         month = month(date)) %>% 
  group_by(year, month) %>% 
  nest() %>% 
  ungroup() %>% 
  inner_join(high, by=c("year","month")) %>% 
  inner_join(low, by=c("year","month")) %>% 
  mutate(high = map2(data, high, ~ .x %>% select(one_of(.y)) %>% apply(1, function(x) mean(x,na.rm=TRUE))),
         low = map2(data, low, ~ .x %>% select(one_of(.y)) %>% apply(1, function(x) mean(x,na.rm=TRUE)))) %>% 
  mutate(CMA = map2(high, low, ~ .x - .y)) %>% 
  mutate(CMA = map2(CMA, data, ~ .x %>% data.frame(date=.y$date, CMA=.))) %>% 
  select(CMA) %>% 
  unnest()
```


```{ factors}
factor.tmp <- factor.tmp %>% 
  inner_join(RMW, by="date") %>% 
  inner_join(MOM, by="date") %>% 
  inner_join(CMA, by="date")
factor.tmp <- factor.tmp %>% 
  mutate(CMA = scale(CMA),
         RMW = scale(RMW),
         MOM = scale(MOM))
saveRDS(factor.tmp, "E:/Git/Bloomberg/data/factors.RDS")
```

