---
title: "Bloombrtgまとめ"
author: "Yutaka Kuroki"
date: "2017年12月7日"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(tidyverse)
library(foreach)
library(doParallel)
library(lubridate)
```


# はじめに

# データの準備

```{r data}
d.tmp <- read.csv("E:/Git/Bloomberg/data/assets.csv")
rownames(d.tmp) <- d.tmp[,1]
d <- data.frame(date = as.Date(rownames(d.tmp)[-1]),
                apply(d.tmp[,-1] %>% na.omit(), 2, function(x){diff(log(x))}))
```

```{r factor}
factor.tmp <- read_csv("E:/Git/Bloomberg/data/factors_8.csv") %>% 
  mutate(date = as.Date(date)) 
```

```{r lasso}

f.lasso <- function(return, factor) {
  registerDoParallel(cores = 7)
  a <- foreach(i = 1:(return %>% dplyr::select(-date) %>% ncol()),
               .combine = rbind,
               .packages = c("tidyverse", "glmnet"),
               .inorder = TRUE) %dopar% {
                 cv.glmnet(x = factor %>% dplyr::select(-date) %>% as.matrix(),
                           y = return %>% dplyr::select(-date) %>% .[,i] %>% as.matrix(),
                           standardize = TRUE) %>% 
                   coef(s = "lambda.min") %>% 
                   .[,1]
          }
  stopCluster(get(".revoDoParCluster", pos = doParallel:::.options))
    rownames(a) <- return %>% 
    dplyr::select(-date) %>% 
    colnames()
  return(a)
}

```

```{r}
return <- d %>% 
  as_tibble() %>% 
  mutate(year = year(date),
         last_month = month(date)) %>% 
  group_by(year, last_month) %>% 
  nest() %>% 
  mutate(lag1 = lag(data),
         lag2 = lag(data, 2),
         test = lead(data, 1)) %>% 
  mutate(return = map2(lag1, data, ~rbind(.x,.y))) %>% 
  mutate(return = map2(lag2, return, ~rbind(.x,.y))) %>% 
  dplyr::select(year, last_month,return, test) %>% 
  slice(3:n())

factor <- factor.tmp %>% 
  as_tibble() %>% 
  mutate(year = year(date),
         last_month = month(date)) %>%
  group_by(year,last_month) %>% 
  nest() %>% 
  mutate(lag1 = lag(data),
         lag2 = lag(data,2)) %>% 
  mutate(factor = map2(lag1, data, ~rbind(.x,.y))) %>% 
  mutate(factor = map2(lag2, factor, ~rbind(.x,.y))) %>% 
  dplyr::select(year, last_month,factor) %>% 
  slice(3:n()) 

data <- return %>% 
  left_join(factor, by = c("year", "last_month")) %>% 
  mutate(return = map2(return, factor, ~semi_join(.x, .y, by="date")) %>% as.matrix(),
         factor = map2(factor, return, ~semi_join(.x, .y, by="date")) %>% as.matrix()) %>% 
  mutate(lasso = map2(return, factor, ~f.lasso(.x,.y))) %>%   mutate(replicate = map(lasso,
                         ~diag(5) %*% MASS::ginv(as.matrix(.x)[,-1]) )) 
data <- data %>% 
  mutate(riskpremium = map2(lasso, replicate,
                            ~apply(t(.y), 2 ,function(x) sum(x * .x[,1])))) %>% 
  mutate(riskpremium = map(riskpremium, ~cbind(value=.x, key=c("TOPIX", "VIX", "Value", "Size", "JPY_USD")) %>% 
                             as_tibble()))%>% 
  mutate(highest = map_chr(riskpremium, ~filter(.x, value == max(value))$key)) %>% 
  #####################################################
  mutate(top100 = map2(lasso, highest,
                       ~rownames_to_column(data.frame(.x)) %>% 
                         arrange(desc(.y)) %>% 
                         head(100)))%>% 
  mutate(portfolio = map(top100, ~filter(.x, min_rank(desc(X.Intercept.)) <= 30)$rowname))%>% 
  slice(1:(n()-1)) %>% 
  mutate(ret.port = map2(test, portfolio, 
                           ~dplyr::select(.x, one_of(.y))))%>% 
  mutate(ret.port2 = map_dbl(ret.port, ~mean(apply(.x, 2, function(x) exp(sum(x))))))
##################################################



  mutate(top100 = map2(lasso, highest,
                       ~filter(rownames_to_column(data.frame(.x)), min_rank(desc(.y)) <= 100)))%>% 
  mutate(portfolio = map(top100, ~filter(.x, min_rank(desc(X.Intercept.)) <= 30)$rowname))%>% 
  slice(1:(n()-1)) %>% 
  mutate(ret.port = map2(test, portfolio, 
                           ~dplyr::select(.x, one_of(.y))))%>% 
  mutate(ret.port2 = map_dbl(ret.port, ~mean(apply(.x, 2, function(x) exp(sum(x))))))
  #テスト部分の用意

```


```{r ff3}

factor.ff3 <- factor.tmp %>% 
  as_tibble() %>% 
  dplyr::select(-VIX, -JPY_USD) %>% 
  mutate(year = year(date),
         last_month = month(date)) %>%
  group_by(year,last_month) %>% 
  nest() %>% 
  mutate(lag1 = lag(data),
         lag2 = lag(data,2)) %>% 
  mutate(factor = map2(lag1, data, ~rbind(.x,.y))) %>% 
  mutate(factor = map2(lag2, factor, ~rbind(.x,.y))) %>% 
  dplyr::select(year, last_month,factor) %>% 
  slice(3:n()) 

data.ff3 <- return %>% 
  left_join(factor.ff3, by = c("year", "last_month")) %>% 
  mutate(return = map2(return, factor, ~semi_join(.x, .y, by="date")),
         factor = map2(factor, return, ~semi_join(.x, .y, by="date"))) %>% 
  mutate(lasso = map2(return, factor, ~f.lasso(.x,.y))) %>% 
  mutate(replicate = map(lasso,
                         ~diag(3) %*% MASS::ginv(as.matrix(.x)[,-1]) )) %>%
  mutate(riskpremium = map2(lasso, replicate,
                            ~apply(t(.y), 2 ,function(x) sum(x * .x[,1])))) %>% 
  mutate(riskpremium = map(riskpremium, ~cbind(value=.x, key=c("TOPIX", "Value", "Size")) %>% 
                             as_tibble()))%>% 
  mutate(highest = map_chr(riskpremium, ~filter(.x, value == max(value))$key)) %>% 
  mutate(top100 = map2(lasso, highest,
                       ~filter(rownames_to_column(data.frame(.x)), min_rank(desc(Value)) <= 100))) %>% 
  mutate(portfolio = map(top100, ~filter(.x, min_rank(desc(X.Intercept.)) <= 30)$rowname))%>% 
  slice(1:(n()-1)) %>% 
  mutate(ret.port = map2(test, portfolio, 
                           ~dplyr::select(.x, one_of(.y))))%>% 
  mutate(ret.port2 = map_dbl(ret.port, ~mean(apply(.x, 2, function(x) exp(sum(x))))))
  #テスト部分の用意

```

```{r GRS}
data.GRS <- inner_join(factor.tmp, d, by="date")

return.mat <- data.GRS %>% 
  dplyr::select(ends_with("Equity")) %>% 
  as.data.frame()
factor.mat <- data.GRS %>% 
  dplyr::select(one_of(c("TOPIX", "VIX", "Value", "Size", "JPY_USD"))) %>% 
  as.data.frame()


GRS <- return.mat %>% 
  as_tibble() %>% 
  gather(key, value) %>% 
  group_by(key) %>% 
  nest() %>%
  mutate(data = map(data, ~data.frame(return = unlist(.x), factor.mat))) %>% 
  mutate(lm.fit = map(data, ~lm(return ~ ., data=.x))) %>% 
  mutate(coef = map(lm.fit, ~.x$coefficients)) 
a <- GRS %>% 
  dplyr::select(key, coef) %>% 
  mutate(coef = map(coef, ~as.data.frame(.x) %>% 
                      rownames_to_column))%>% 
  unnest() %>% 
  spread(rowname, .x) %>% 
  mutate(Size = Size > median(Size),
         TOPIX = TOPIX > median(TOPIX),
         VIX = VIX > median(VIX),
         JPY_USD = JPY_USD > median(JPY_USD),
         Value = Value > (median(Value))) %>% 
  right_join(GRS, by = "key") %>% 
  dplyr::select(-lm.fit, -coef) %>% 
  mutate(return = map(data, ~ .x$return)) %>%
  group_by(JPY_USD, TOPIX, Value, Size, VIX) %>% 
  nest() %>% 
  mutate(return.port = map(data, ~ .x$return %>% 
                             do.call("cbind",.) %>% 
                             rowMeans())) %>% 
  mutate(port = 1:n())
  
b <- a %>% 
  dplyr::select(port, return.port) %>% 
  unnest() %>% 
  group_by(port) %>% 
  mutate(index = 1:n()) %>% 
  spread(port, return.port) %>% 
  dplyr::select(-index) %>% 
  as.data.frame()
  
a$data[[1]]

GRS.test(b, factor.mat ) 
```


```{r }
(data$return[[1]][,-1] - as.matrix(data$factor[[1]][,-6]) %*% t(data$lasso[[1]][,-1])) %>% as.matrix() %>% as.vector() %>%  summary()
```

