---
title: "ggnet"
author: "Yutaka Kuroki"
date: "2018年1月14日"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(GGally)
library(ggnetwork)
library(sna)
```

```{r}
net <- rgraph(10, mode = "graph", tprob = 0.5)
net <- network(net, directed = FALSE)

network.vertex.names(net) <- letters[1:10]

ggnet2(net)
ggnet2(net,
       node.size=10,
       edge.size = 2,
       color = rep(c("tomato", "steelblue"),5))

# 位置の設定mode
ggnet2(net, mode = "circle")
ggnet(net, mode = "kamadakawai")

ggnet2(net, mode = "fruchtermanreingold", 
       layout.par = list(cell.jitter = 0.75))
ggnet2(net, mode = "target", 
       layout.par = list(niter = 100))

# 頂点に属性を割り当て
net %v% "phono" = ifelse(letters[1:10] %in% c("a", "e", "i"), "vowel", "consonant")
ggnet2(net, color="phono")

net %v% "color" = ifelse(net %v% "phono" == "vowel", "steelblue", "tomato")
ggnet2(net, color = "color")

```


```{r}
#gs <- read_rds("E:/Git/Bloomberg/data/result_glasso.RDS")
data <- gs$result[[6]] 
a <- list()
for(i in 1:nrow(data)){
  a[[i]] <- abs(data$glasso[[i]]$wi) > 0.0000001
}
a %>% 
  map(~ abs(.x) > 0.00000001) %>% 
  map(~ as_tibble(.x) %>% 
        mutate(index=1:6) %>% 
        gather(key,value,-index)) %>% 
  do.call("rbind",.) %>% 
  group_by(index, key) %>% 
  summarise(sum=sum(value)) %>% 
  ungroup() %>% 
  spread(key, sum)

for(i in 1:6){
  for(j in 1:6){
    tmp[i,j] <-  (tmp[i,j]/sqrt(tmp[i,i]*tmp[j,j]))
  }
}
diag(tmp) <- 0
colnames(tmp) <- colnames(data$factor[[1]][,-1])
rownames(tmp) <- colnames(data$factor[[1]][,-1])
tmp3 <- graph.adjacency(tmp ,
                        mode = "undirected",
                        weighted=TRUE,
                        diag = FALSE) %>% 
  asNetwork()
tmp3 %v% "factor" <- colnames(data$factor[[1]][,-1])
tmp4 <- ggnetwork(tmp3, layout = "circle")
# 
# tmp5 <- data.frame(x = tmp4$x + rnorm(length(tmp4$x)), 
#                    y = tmp4$y + rnorm(length(tmp4$y)),
#                    tmp4[,-c(1,2)])

# ggplot(tmp4, aes(x=x, y=y, xend=xend, yend=yend))+
#   geom_edges(colour = "black", size=1)+
#   geom_nodes(colour = "skyblue", size=15)+
#   geom_nodetext(aes(label=factor), colour = "black", fontface="bold")+
#   geom_edgetext(aes((2*x+xend)/3,(2*y+yend)/3,label=round(weight,3)))+
#   theme_minimal()+
#   theme(axis.text = element_blank(),
#         axis.title = element_blank(),
#         panel.background = element_rect(fill="white", colour="white"),
#         panel.grid = element_blank())


ggplot(tmp4,aes(x,y,xend=xend,yend=yend))+
  geom_segment(size=1.2, colour="grey75")+
  geom_point(aes(x=x,y=y), size=15, colour = "skyblue")+
  geom_text(aes(x=x, y=y, label=factor), colour="black")+
#  geom_segment(aes(x=(x+xend)/2,y=(y+yend)/2,xend=(2*x+xend)/3+0.1,yend=(2*y+yend)/3))+
  geom_text(aes((2*x+3*xend)/5,(y*2+yend*3)/5,label=round(-weight,3)), fontface="bold")+
#  geom_edgetext(aes(x=(2*x+xend)/3,y=(2*y+yend)/3,label=round(weight,3)))+
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank())+
  scale_x_continuous(limits=c(-0.1,1.1))+
  scale_y_continuous(limits = c(-0.1,1.1))
```


```{r}
0.5*log(2*pi/tmp[1,1]) + 1/2*tmp[1,1]*(tmp[,1] %*% )^2
```

