---
title: "sparse"
author: "Yutaka Kuroki"
date: "2017年12月14日"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      eval=FALSE,
                      include=FALSE)
```

```{r library}
library(tidyverse)
library(lubridate)
library(glasso) # グラフィカルLasso
library(igraph) # プロット
library(spaceExt) # glasso with EM
library(GGally)
```

# データの準備う
```{r assets}
d.tmp <- read.csv("E:/Git/Bloomberg/data/assets.csv")
rownames(d.tmp) <- d.tmp[,1]
d <- data.frame(date = as.Date(rownames(d.tmp)[-1]),
                apply(d.tmp[,-1] %>% na.omit(), 2, function(x){diff(log(x))}))
```

```{r factors}
#factor.tmp <- read.csv("E:/Git/Bloomberg/data/factors.csv")[,-1] %>% 
#  mutate(date = as.Date(Date)) %>% 
#  dplyr::select(-Date)
factor.tmp <- read_csv("E:/Git/Bloomberg/data/factors_8.csv") %>% 
  rename(MKT = TOPIX) %>% 
  select(date,CMA, HML, MOM, RMW, SMB, MKT)
```
factor.tmp %>% mutate(Size = scale(Size),Value=scale(Value), )
```{r data}
return <- d %>% 
  as_tibble() %>% 
  mutate(year = year(date),
         last_month = month(date)) %>% 
  group_by(year, last_month) %>% 
  nest() %>% 
# ローリングの窓の長さ3ヶ月。オーバーラップ2ヶ月
  mutate(lag1 = lag(data),
         lag2 = lag(data, 2),
         test = lead(data, 1)) %>%
  mutate(return = map2(lag1, data, ~rbind(.x,.y))) %>% 
  mutate(return = map2(lag2, return, ~rbind(.x,.y))) %>% 
  dplyr::select(year, last_month,return, test) %>% 
  slice(3:(n()-1))

factor <- factor.tmp %>% 
  as_tibble() %>% 
  mutate(date = as.Date(date),
         year = year(date),
         last_month = month(date)) %>%
  group_by(year,last_month) %>% 
  nest() %>% 
# ローリング
  mutate(lag1 = lag(data),
         lag2 = lag(data,2),
         test_f = lead(data,1)) %>% 
  mutate(factor = map2(lag1, data, ~rbind(.x,.y))) %>% 
  mutate(factor = map2(lag2, factor, ~rbind(.x,.y))) %>% 
  dplyr::select(year, last_month,factor,test_f) %>% 
  slice(3:(n()-1)) 

data <- return %>% 
  left_join(factor, by = c("year", "last_month")) %>% 
  mutate(test = map2(test, test_f, 
                     ~semi_join(.x, .y, by="date") %>% 
                       select(-date) %>% 
                       as.data.frame()), 
         return = map2(return, factor, ~semi_join(.x, .y, by="date")),
         factor = map2(factor, return, ~semi_join(.x, .y, by="date"))) %>% 
  mutate(zy = map2(factor, return, ~cov(.y[,-1], .x[,-1])))
```

```{r hogehoge}
hogehoge <- function(rho){
  a <- data %>% 
    mutate(glasso = map(factor,
                        ~.x %>% 
                          dplyr::select(-date) %>% 
                          cov() %>% 
                          glasso(rho=rho))) %>% 
    mutate(wi = map(glasso, ~.x$wi)) %>% 
    mutate(beta = map2(wi, zy, ~ .x %*% t(.y))) %>% 
    mutate(yhat = map2(test_f, beta, ~ as.matrix(.x[,-1]) %*% .y)) %>% 
    mutate(resid = map2(test, yhat, ~ .x - .y))
  return(a)
}
```


```{r grid search}
gs <- tibble(rho = c(seq(0,0.2,0.025),seq(0.3,1,0.1))) %>% 
  mutate(result = map(rho, ~hogehoge(.x))) %>% 
  mutate(sse = map_dbl(result, ~sum(.x$resid^2)))
saveRDS(gs, "E:/Git/Bloomberg/data/result_glasso.RDS")
```

```{r plot}

best %>% select(test, yhat) %>% mutate(a = map2(test, yhat, ~ cbind(.x[,1],.y[,1]))) %>% .$a %>% .[[11]] %>% matplot(type="l")

best$factor[[1]] %>% select(-date) %>% gather(key,value) %>% group_by(key) %>% summarise(mean=mean(value),sd=sd(value)) %>% ggplot(aes(sd,mean,group=key))+geom_text(aes(label=key))
```


```{r riskpremium}
# SSEが最も良かったrho=0.1を使用する

best <- gs %>% 
  filter(sse == min(sse)) %>% 
  select(result) %>% 
  unnest() %>% 
  select(-wi,-zy)

# 各期のno.1ファクターを狙った
a <- best %>% 
  mutate(ratio = map(factor,
                     ~ .x %>%
                       select(-date) %>% 
                       gather(key,value) %>% 
                       group_by(key) %>% 
                       summarise(ratio = mean(value)/sd(value)))) %>% 
  mutate(highest = map_dbl(ratio, 
                       ~ which(.x$ratio == max(.x$ratio)))) %>% 
  mutate(top100 = map2(beta,highest,
                       ~ .x[.y,] %>% 
                         sort(decreasing=TRUE) %>%
                         head(30) %>% 
                         names())) %>% 
  mutate(ret.port = map2_dbl(test, top100,
                       ~ .x %>% 
                         select(one_of(.y)) %>% 
                         apply(2,function(x) exp(sum(x))) %>% 
                         mean()))

# 各ファクターへの係数top30
a <- best %>% 
  mutate(CMA = map(beta,
                     ~ .x[1,] %>% 
                       sort(decreasing=TRUE) %>% 
                       head(30) %>% 
                       names()),
         HML = map(beta,
                     ~ .x[2,] %>% 
                       sort(decreasing=TRUE) %>% 
                       head(30) %>% 
                       names()),
         MOM = map(beta,
                     ~ .x[3,] %>% 
                       sort(decreasing=TRUE) %>% 
                       head(30) %>% 
                       names()),
         RMW = map(beta,
                     ~ .x[4,] %>% 
                       sort(decreasing=TRUE) %>% 
                       head(30) %>% 
                       names()),
         SMB = map(beta,
                     ~ .x[5,] %>% 
                       sort(decreasing=TRUE) %>% 
                       head(30) %>% 
                       names()),
         MKT = map(beta,
                     ~ .x[6,] %>% 
                       sort(decreasing=TRUE) %>% 
                       head(30) %>% 
                       names())) %>% 
  mutate(ret.CMA = map2_dbl(test, CMA,
                            ~ .x %>% 
                              select(one_of(.y)) %>% 
                              apply(2, function(x) exp(sum(x))) %>% 
                              mean()),
         ret.HML = map2_dbl(test, HML,
                            ~ .x %>% 
                              select(one_of(.y)) %>% 
                              apply(2, function(x) exp(sum(x))) %>% 
                              mean()),
         ret.MOM = map2_dbl(test, MOM,
                            ~ .x %>% 
                              select(one_of(.y)) %>% 
                              apply(2, function(x) exp(sum(x))) %>% 
                              mean()),
         ret.RMW = map2_dbl(test, RMW,
                            ~ .x %>% 
                              select(one_of(.y)) %>% 
                              apply(2, function(x) exp(sum(x))) %>% 
                              mean()),
         ret.SMB = map2_dbl(test, SMB,
                            ~ .x %>% 
                              select(one_of(.y)) %>% 
                              apply(2, function(x) exp(sum(x))) %>% 
                              mean()),
         ret.MKT = map2_dbl(test, MKT,
                            ~ .x %>% 
                              select(one_of(.y)) %>% 
                              apply(2, function(x) exp(sum(x))) %>% 
                              mean())) %>% 
  select(year, last_month, starts_with("ret"), -return) %>% 
  mutate_at(vars(starts_with("ret")), cumprod) %>% 
  rbind(c(2015,1,1,1,1,1,1,1),c(2015,2,1,1,1,1,1,1),.,c(2017,5,1,1,1,1,1,1),c(2017,6,1,1,1,1,1,1)) %>% 
  mutate(year = lead(year,2),
         last_month = lead(last_month,2)) %>% 
  slice(2:(n()-2)) %>% 
  gather(key, value, -year, -last_month) %>% mutate(date = make_date(year,last_month))

cb_palette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00")
a %>% 
  ggplot(aes(date, value, group=key, colour=key))+
  geom_line(size=1)+
  theme_bw()+
  scale_color_manual(values=cb_palette)

```

# スライドの構成

1. Introduction
    - background
    - motivation
    - purpose
2. Methods
    - factor model
    - Graphical Lasso
    - precision matrix at linear regression
3. Data
    - assets
    - factor
4. Results
    - 
5. Discussion
6. Conclusions

# lmとの比較

```{r lm}

lm.fit<- data %>% 
  mutate(lm = map2(factor, return,
                   ~ solve(t(.x %>% mutate(date=1)) %*% as.matrix(.x %>% mutate(date=1))) %*% t(.x %>% mutate(date = 1)) %*% as.matrix(.y[,-1]))) %>% 
  mutate(yhat_lm = map2(lm, test_f,
                        ~as.matrix(.y %>% mutate(date=1)) %*% as.matrix(.x))) %>% 
  mutate(resid_lm = map2(test, yhat_lm,
                         ~ (.x - .y)^2)) %>% 
  mutate(resid = map_dbl(resid_lm, sum))
lm.fit$resid %>% sum()
gs
```


```{r compare}
lm.fit %>% 
  mutate(sse = map2_dbl(test, yhat_lm, ~(.x-.y)^2 %>% sum())) %>% select(sse) %>% sum
best %>% 
  mutate(sse = map2_dbl(test, yhat, ~(.x-.y)^2 %>% sum())) %>% select(sse) %>% sum

data %>% 
  mutate(lm = map2(factor, return,
                   ~ solve(t(.x[,-1]) %*% as.matrix(.x[,-1])) %*% t(.x[,-1]) %*% as.matrix(.y[,-1]))) %>% 
  mutate(yhat_lm = map2(lm, test_f,
                        ~as.matrix(.y[,-1]) %*% as.matrix(.x))) %>% 
  mutate(sse = map2_dbl(test, yhat_lm, ~(.x-.y)^2 %>% sum())) %>% select(sse) %>% sum()
#413.445
```

```{r}
lm.fit %>% 
  mutate(resid = map2(test, yhat_lm, ~.x-.y)) %>% select(resid) %>% unlist() %>% summary()
best %>% 
  mutate(resid = map2(test, yhat, ~.x-.y)) %>% select(resid) %>% unlist() %>% summary()
```

# top100

```{r top100}
x <- best %>% 
  mutate(top100_name = map(test, 
                      ~ apply(.x, 2, function(x) exp(sum(x))) %>% 
                        sort(decreasing=TRUE) %>% 
                        head(30) %>% 
                        names())) %>% 
  mutate(top100 = map2(beta, top100_name,
                       ~ .x %>% 
                         as.data.frame() %>% 
                         select(one_of(.y)))) %>% 
  mutate(under = map2(beta, top100_name,
                       ~ .x %>% 
                         as.data.frame() %>% 
                         select(-one_of(.y)))) 

x$top100[[1]] %>% t() %>% pairs(col="blue")

x[1,] %>% 
  select(top100, under) %>% 
  unnest() %>% 
  gather(key, value) %>% 
  mutate(index = rep(1:6, n()/6)) %>% 
```

# Figures

```{r factors}
factor.tmp %>% 
  mutate(date = as.Date(date)) %>% 
  gather(key,value,-date) %>% 
  
  ggplot(aes(date,value,group=key))+
  geom_line(size=0.2)+
  scale_x_date(date_label="%Y")+
  facet_wrap(~key)+
  theme_bw()+
  theme(strip.background = element_rect(fill="aquamarine"))
```


```{r factors_cor}
pm <- ggpairs(
    factor.tmp[, c(2,3,4,5,6,7)],
    upper = list(continuous = wrap("cor", colour="black", size = 5),
                 combo = "box_no_facet", discrete = "facetbar", na = "na"),
    diag = list(continuous = wrap("barDiag", fill="skyblue", colour="blue", size=0.3), discrete = "barDiag", na = "naDiag"),
    lower = list(continuous = wrap("points",size=0.1), combo = "dot_no_facet")
)
pm <- pm +
  theme_bw()+
  theme(strip.background = element_rect(fill="aquamarine"),
        strip.text = element_text(face = "bold", size=rel(1)))

p_(pm)
```

```{r gridsearch}
gs %>% 
  ggplot(aes(rho, sse)) +
  geom_line(size=1)+
  theme_bw()+
  scale_x_continuous(breaks=seq(0,1,0.1))+
  labs(y="SSE")+
  geom_hline(yintercept = min(gs$sse), size = 1.2, colour="red", linetype="dashed")+
  annotate("text",label="SSE=386.1207", x=0.8,y=min(gs$sse)+4, size=5)+
  geom_vline(xintercept = 0.125, size=1.2, colour="blue", linetype="dashed")+
  annotate("text", label="rho=0.125", x=0.2, y=490., size=5)

```

# winner loser

```{r}
wl <- best %>% 
  mutate(test.ret = map(test,
                        ~ apply(.x,2,function(x) exp(sum(x))))) %>% 
  mutate(winner = map(test.ret, 
                      ~ .x %>% 
                        sort(decreasing = TRUE) %>% 
                        head(100) %>% 
                        names()),
         loser = map(test.ret,
                     ~ .x %>% 
                       sort() %>% 
                       head(100) %>% 
                       names())) %>% 
  mutate(winner = map2(beta, winner,
                       ~ .x %>% 
                         as_tibble() %>% 
                         select(one_of(.y)) %>% 
                         mutate(factor = colnames(factor.tmp[,-1])) %>% 
                         gather(ticker, value, -factor)),
         loser = map2(beta, loser,
                      ~ .x %>% 
                        as_tibble() %>% 
                        select(one_of(.y)) %>% 
                        mutate(factor = colnames(factor.tmp[,-1])) %>% 
                        gather(ticker,value,-factor))) %>% 
  select(winner, loser)

wl %>% 
  gather(key, value) %>% 
  unnest() %>% 
  ggplot(aes(value, group=key))+
  geom_density()+
  facet_wrap(~factor)+
  theme_bw()+
  theme(strip.background = element_rect(fill="aquamarine"))+
  ggtitle("Winner  vs  Loser")
```


